In [8]:
# flask 
import flask # 웹서버 기능      5000번 포트로 서비스를 하는게 디폴트 값


In [10]:
#numpy 시작

import matplotlib    # 시각화 패키지
import numpy as np      # 별칭 class
print( np.__version__)          #상위 오브젝트가 가진 속성
def pprint(arr):            # ndarray : 넘파이의 기본 데이터 배열
    print("type:{}".format(type(arr)))     
    print("shape:{}, dimention:{}, dtype:{}".format(arr.shape, arr.ndim, arr.dtype))          
    print("Array's Data :\n", arr)
    # 숫자의 디폴트는 int 32 형이다 
arr = [1.0,2.0,3.0]       # 리스트 
a = np.array([1.0,2.0,3.0])           #ndarray 생성함수 ( 매개변수: 리스트)
pprint(a)

1.16.5
type:<class 'numpy.ndarray'>
shape:(3,), dimention:1, dtype:float64
Array's Data :
 [1. 2. 3.]


In [15]:
# 인스턴스상태가 되어진다. 
a= np.array([0,1,2,3,4,5,6,7,8,9])   # ndarray 상태
print(id(a))                           # python core 주소값 확인
print(a.size)                                 # 데이터 개수
print(a.astype(np.float32))                      # 데이터 타입 변경, numpy 는 행중심 , 데이터는 동질적
print(a.dtype.itemsize * a.size)                      #  전체 메모리 사이즈 (바이트로)
# iterator for in range문을 사용하면 리스트를 만든다
# arange 를 사용하면 ndarray를 만든다
a = np.arange(100)
a

2415306376176
10
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
40


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [17]:
## ndarray 초기화 함수들 

print(np.zeros((3,4)))
print(np.ones((2,3,4),dtype = np.int16))      #데이터 타입을 지정해줄수 있습니다. (면, 행, 열)
print(np.full((2,2),7))
print(np.eye(4))      # 대각 행렬  identity  # 행렬연산에서의 항등원
print(np.empty((4,2)))   # 쓰레기 값이 나온다. # 주소값을 지우고 남은것임. 

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
[[7 7]
 [7 7]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 7.07502005e-321]
 [1.24611741e-306 1.11261027e-306]]


In [18]:
a = np.arange(0,100,10)        # ndarray 
indices = [1,5,-1]             # 리스트 
print(indices)
b = a[indices]                  #리스트를 첨자로 사용한다. 
print(a)
print(b)


[1, 5, -1]
[ 0 10 20 30 40 50 60 70 80 90]
[10 50 90]


In [27]:
a = np.arange(11,36)         #여기서 1차원으로 만들어진다 
print(a)                   
a.shape = (5,5)                   # 이걸 5,5행으로 만들어 줘라 하고 실행 시킴
print(a)                                # 1차원 배열의 개수가 행렬의 정상 모양을 갖추도록 해줘야한다. 
print(type(a))
print(a.dtype)
print(a.size)
print(a.shape)
print(a.ndim)
#dir(a)
print(a.nbytes)                # 100바이트 25 * 4
print(a.strides)             # (20,4) 다음열의 데이터는 몇 바이트를 건너 뛰어야 하는가. 
                            # 다음 행은 몇 바이트를 건너뛰어야 하는가?  한 행에 5개의 숫자 이므로 4*5를 사용 즉 20 바이트 
                                # 넘파이에서는 메모리에 행으로 즉 일렬로 쭉 저장되어 있기 때문에 사용

[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35]
[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]
<class 'numpy.ndarray'>
int32
25
(5, 5)
2
100
(20, 4)


In [29]:
arr = np.arange(10)
print(type(arr))
print(arr)
print(arr[5])
print(arr[5:8]) # 마지막 불포함  
arr[5:8]= 12          # 데이터 update
print(arr[1:6])

<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]
5
[5 6 7]
[ 1  2  3  4 12]


In [31]:
#numpy 첨자 생략이 불가 [,4]

arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d[0])      # 행우선 이므로 첫번째 행이 온다 
print(arr2d[0][2])         
print(arr2d[0,2])
print(arr2d[:2])
print(arr2d[:2,1:])
print(arr2d[1,:2])
print(arr2d[2, :1])
arr2d[:2,:1 ] = 0
arr2d[:2,:1] = 0
print(arr2d)


[1 2 3]
3
3
[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]]
[4 5]
[7]
[[0 2 3]
 [0 5 6]
 [7 8 9]]


In [33]:
# 실제 저장은 일렬로 사람이 데이터를 다루는 것은 입체로 
# 행렬 연산에서 앞의 행렬연수와 뒤의 행렬의 행수를 일치 시켜야 행렬의 곱이 가능
# 행렬곱에서 행렬 앞뒤로 바뀌면 안된다. 

print("스트라이드의 값", np.ones((3,4,5), dtype = np.float64).strides)         

스트라이드의 값 (160, 40, 8)


In [61]:
# 문제
arr3d = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
print(arr3d)
print(arr3d.dtype)
print(arr3d.size)
print(arr3d.shape)
print(arr3d.ndim)
print('첫면은=',arr3d[0])  # 0번면
print('첫면 첫행, 첫요소는 = ', arr3d[0][0][0])
print(arr3d[1][0][1])
print(arr3d[1][1][2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
int32
12
(2, 2, 3)
3
첫면은= [[1 2 3]
 [4 5 6]]
첫면 첫행, 첫요소는 =  1
8
12


In [59]:
old_values = arr3d    # 대입 : 주소를 복사 
arr3d[0] = 42
print('값의 변경후')
print(arr3d)
print('이전 값으로 복구')
arr3d = old_values      ## 이전값을 가지고 백업 시켜 놓아도 주소가 같아지기 때문에 백업이 되지 않는다
print(arr3d)             ## 그래서 copy라는 함수를 사용하여 백업을 시킨다. 


값의 변경후
[[[42 42 42]
  [42 42 42]]

 [[ 7  8  9]
  [10 11 12]]]
이전 값으로 복구
[[[42 42 42]
  [42 42 42]]

 [[ 7  8  9]
  [10 11 12]]]


In [62]:
old_values = arr3d.copy()    # 대입 : 주소를 복사 
arr3d[0] = 42
print('값의 변경후')
print(arr3d)
print('이전 값으로 복구')
arr3d = old_values      ## 이전값을 가지고 백업 시켜 놓아도 주소가 같아지기 때문에 백업이 되지 않는다
print(arr3d)   

값의 변경후
[[[42 42 42]
  [42 42 42]]

 [[ 7  8  9]
  [10 11 12]]]
이전 값으로 복구
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [66]:
Z = np.arange(36)
print(Z)
Z = Z.reshape(6,6)
reshape2 = Z.reshape((2,3,6))
print(reshape2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]
[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]]

 [[18 19 20 21 22 23]
  [24 25 26 27 28 29]
  [30 31 32 33 34 35]]]


In [14]:
arr = np.arange(32).reshape((8,4))
print(arr)
print()
print(arr[[1,5,7,2]])          ##행을 인덱싱 행중심이라 앞에는 행을 의미 
print()
print(arr[[-1,-5,-7,-2]])
print()
print(arr[[1,5,7,2],[0,3,1,2]])
print()
print(arr[[1,2,5,7]][:,[0,1,2,3]]) #fancy 인덱싱
print()
print(arr[[1,5,7,2]][:,[0,3,1,2]])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]

[[ 4  5  6  7]
 [20 21 22 23]
 [28 29 30 31]
 [ 8  9 10 11]]

[[28 29 30 31]
 [12 13 14 15]
 [ 4  5  6  7]
 [24 25 26 27]]

[ 4 23 29 10]

[[ 4  5  6  7]
 [ 8  9 10 11]
 [20 21 22 23]
 [28 29 30 31]]

[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


In [48]:
# 문제 

arr = []
for i in range(6):
    ad = []
    for j in range(6):
        ad.append(i*10 +j)
    arr.append(ad)
print(arr)
arr = np.array(arr).reshape((6,6))
print()
print(arr)
print('\n')
print(arr[[0,1,2,3,4],[1,2,3,4,5]])  #주황
print(arr[[0,2,5], [2,2,2]]) # 빨강           print(arr[[0,2,5],2])


print(arr[3:6][:,[0,2,5]]) # 하늘색

[[0, 1, 2, 3, 4, 5], [10, 11, 12, 13, 14, 15], [20, 21, 22, 23, 24, 25], [30, 31, 32, 33, 34, 35], [40, 41, 42, 43, 44, 45], [50, 51, 52, 53, 54, 55]]

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]


[ 1 12 23 34 45]
[ 2 22 52]
[[30 42 55]
 [30 42 55]
 [30 42 55]]
[[30 32 35]
 [40 42 45]
 [50 52 55]]


In [57]:
print( arr [:][:,2])     # 빨강

print(arr [0,[3,4]])          # 0번 행에 대해서 3,4 주황

print(arr [[2,4]][:,[0,2,4]])

print(arr [4:][:,[4,5]])

[ 2 12 22 32 42 52]
[3 4]
[[20 22 24]
 [40 42 44]]
[[44 45]
 [54 55]]


In [71]:
x = np.array ([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])        #4*3 행렬
print(x)
print()
v = np.array ([1,0,1])
print(y)
print()
print('타일 출력')
vv= np.tile(v,(4,1))  # v라는 옴을 행으로 
print(vv)
print()
y = x+vv
print(y)
x+v           #각 행이 맞지 않지만 연산이 가능하다 이게 바로 broadcast   --> 배열 연산에서는 양쪽 차원이 일치해야한다. 
# 각 행이나 열 요소중에 차원이 일치하는것과 브로드 캐스팅한다. 
x+3            # 상수는 모든 데이터에 더해진다. 

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]

타일 출력
[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [79]:
x =np.arange(6).reshape((3,2))
print(x)
# 거듭제곱 (행열곱)
 # x @ x   #이러면 에러난다 앞의 행렬의 열수와 뒤의 행렬의 행수가 일치해야한다. 
# 즉 (3 *2 )  (3*2 )를 전치해줘야한다 
# (3*2)(2*3)으로
# 전치행렬
print(x@x.T)          ## 행렬 곱이다. 
print(np.transpose(x))

[[0 1]
 [2 3]
 [4 5]]
[[ 1  3  5]
 [ 3 13 23]
 [ 5 23 41]]
[[0 2 4]
 [1 3 5]]


In [88]:
# tranpose

arr = np.arange(24).reshape((2,3,4))         # 2면 3행 4열 
print(arr ,'\n')
print('----------------')
print(arr.transpose((1,0,2)))                      #3면 2행 4열
print('----------------')
print(arr.transpose((0,2,1)))                       # 2면 4행 3열 

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]] 

----------------
[[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]
----------------
[[[ 0  4  8]
  [ 1  5  9]
  [ 2  6 10]
  [ 3  7 11]]

 [[12 16 20]
  [13 17 21]
  [14 18 22]
  [15 19 23]]]


In [94]:
## Boolean indexing(True/False)
### 문자열은 대 소문자를 구분한다. 

names = np.array(['Seoul', 'Daejun', 'chungju', 'seoul', 'chungju',
                 'Daejun', 'Daejun'])
data = np.random.randn(7,4)
print(names == 'Seoul')       #True, False로 나와 있지만 1,0,0,0,0,0 이렇게 매핑 되어 있음 
print(data[names =='Seoul'])  ## 첫번째 있는 0번행만 출력해라 
print(data[names =='Seoul',2:])
print(data[names =='Seoul',3])
print(names != 'Seoul')
print(~(names =='Seoul'))
mask = (names =='Seoul')|(names =='chungju')
print(mask)
print(data[mask])

[ True False False False False False False]
[[ 0.60677861 -1.90549689  0.21004658 -1.6963073 ]]
[[ 0.21004658 -1.6963073 ]]
[-1.6963073]
[False  True  True  True  True  True  True]
[False  True  True  True  True  True  True]
[ True False  True False  True False False]
[[ 0.60677861 -1.90549689  0.21004658 -1.6963073 ]
 [ 0.08160329 -1.3284238   0.3448216  -0.30663429]
 [ 0.82147275 -0.08240642 -0.84644276  1.15303491]]


In [98]:
xarr = np.array([1.1,1.2,1.3,1.4,1.5])
yarr = np.array([2.1,2.2,2.3,2.4,2.5])
cond = np.array([True, False, True, True, False])
print(zip(xarr, yarr, cond))          ## 요소별로 데이터를 묶음, zip 고유 포멧으로 출력 되므로 
print(list(zip(xarr,yarr,cond)))             # 리스트로 바꾸어서 출력해줘야한다. 
result = [(x if c else y)for x,y,c in zip(xarr,yarr,cond)]           # 3 항 연산자
print('result=', result)

result = np.where(cond,xarr,yarr)       #참이면 x값을 출력 거짓이면 y 값을 출력한다. 
print(result)

arr = np.random.randn(4,4)
print(arr)
print(np.where(arr>0,2,-2))          # arr의 값이 0 보다 크다면 2  0보다 작다면 -2 

[(1.1, 2.1, True), (1.2, 2.2, False), (1.3, 2.3, True), (1.4, 2.4, True), (1.5, 2.5, False)]
result= [1.1, 2.2, 1.3, 1.4, 2.5]
[1.1 2.2 1.3 1.4 2.5]
[[ 0.38447848  0.29207352  0.88014954 -1.5959945 ]
 [-0.54172594  0.32900973 -0.44913996  0.24362845]
 [-0.28607989  0.51248145 -0.65319904 -0.02249199]
 [-0.03965195 -0.75281628 -0.52199033 -1.88302661]]
[[ 2  2  2 -2]
 [-2  2 -2  2]
 [-2  2 -2 -2]
 [-2 -2 -2 -2]]


In [122]:
# 문제) 다음 데이터를 이용하여 두개다 참일 떄는 0, cond1이 참일 떄는 1, cond2가 참일 때는 2 그 외일 때는 3으로 처리하여
# 출력 하도록 하시오 

result = []
cond1 = np.array([1,0,1,1,0,0,1],dtype = bool)
cond2  = np.array([0,1,1,1,0,1,1],dtype = bool)
print(cond1)
print(cond2)
result2 = zip(cond1,cond2)
print(result1)
print(list(result1))

for i in range(len(cond1)):
    if(cond1[i]and cond2[i]):
        result.append(0)
    elif cond1[i]:
        result.append(1)
    elif cond2[i]:
        result.append(2)
    else:
        result.append(3)
print('조건문',result)




result =np.where(cond1&cond2, 0, np.where(cond1,1,np.where(cond2,2,3)))
print('3항연산자', result)


result = 1*(cond1&~cond2)+ 2*(cond2&~cond1) + 3*~(cond1 |cond2)
print('수식을 이용한 ',result)

[ True False  True  True False False  True]
[False  True  True  True False  True  True]
[]
조건문 [1, 2, 0, 0, 3, 2, 0]
3항연산자 [1 2 0 0 3 2 0]
수식을 이용한  [1 2 0 0 3 2 0]


In [127]:
x = np.arange (1, 10001)
y = np.arange (10001, 20001)

z = np.zeros_like(x)             #z 행렬과 같은 사이즈의 메모리 공간을 확보해준다. 초기화 
for i in range(10000):
    z[i]= x[i]+y[i]
    
print(z[i])

30000


In [129]:
a = np.array([1,2,3,4])
b = np.array([4,2,2,4])
print(np.all(a==b))      #전체가 참일 때 참
print(np.any(a==b))        #하나라도 참이라면 참
print(np.exp(a))             #지수함수(자연대수 :2.718)



False
True
[ 2.71828183  7.3890561  20.08553692 54.59815003]


In [ ]:
# 선형대수: 선형으로 해결하자 --> 비션형도 잘게 나누어보면 선형으로 보인다. 


In [130]:
# 행렬의 종류 
- 정방행렬 : 정사각형 (행과 열수가 같은 행렬)
- 대칭행렬 : 우상단과 좌하단이 같은 것
- 대각행렬 : scale을 변화시키는 요소 
- 단위행렬(identity) : 행렬곱의 항등원  , 행렬과 역행렬을 곱하면 단위행렬
- 역행렬 : 행렬의 나눗셈을 위해 구해서 곱해지는 행렬 ( 정방행렬만 역행렬이 가능하다 )
- 특이행렬: 역행렬이 없는 행렬 
- 직교행렬: 축의 정직교를 만들어 줘야한다. 각 축간의 내적이 0인 행렬
- 정방행렬이면서 대칭행렬: 공분산행렬, 상관계수행렬, 거리행렬
- 공분산 : 두수간의 관계 ((하나의 수 - 평균) * (다른수 -평균))/n-1\
- 상관계수(표준화): 공분산/ 표준편차의 곱을 이용하여 표준화 시킨다 --> -1~1 사이의 값 

SyntaxError: invalid syntax (<ipython-input-130-0ff0ad1bd826>, line 2)