a = 100
b = 200
print(f'a={a} b={b}')


# Numpy 모듈 불러오기

In [14]:
import numpy as np

# Numpy Array 생성하기

In [16]:
x = [1,2,3,4,5]
y = np.array(x)
y

array([1, 2, 3, 4, 5])

In [17]:
x

[1, 2, 3, 4, 5]

# arange = 파이썬에서의 range와 비슷함//// arange는 소수도 가능하다

In [21]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [23]:
# arange(시작값, 끝값, 스텝)

a = np.arange(0,1,0.1)

a

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [24]:
#뒤에 점은 소수.

a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [26]:
#튜플로 만듬

a = np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [27]:
a = np.zeros((3,3))

a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [30]:
a = np.full((5,3),3.2)
a

array([[3.2, 3.2, 3.2],
       [3.2, 3.2, 3.2],
       [3.2, 3.2, 3.2],
       [3.2, 3.2, 3.2],
       [3.2, 3.2, 3.2]])

In [32]:
# 단위행렬을 생성 대각선으로 값이 있고 나머지는 0
# 단위행렬 * 다른행렬 = 자기 값
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

# 구간 균등분할

In [39]:
# 시작값, 끝값, 나누는 개수 (2이상)
np.linspace(0,100,4)


array([  0.        ,  33.33333333,  66.66666667, 100.        ])

# 차원변환

In [51]:
x = np.arange(9)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [53]:
#1차원 변환


print(x.ndim)

1


In [54]:
x.shape

(9,)

# 2차원변환


In [52]:
#x의 개수와 맞춰서 해야한다. // array를 다시 배치한거임


y = x.reshape(3,3)
y

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [55]:
# 몇 차원인지 파악

y.ndim

2

In [57]:
#몇행 몇 열인지 파악

y.shape

(3, 3)

In [63]:
a = np.arange(1,28).reshape(3,3,3)
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [64]:
# 내가 만든 N차원의 데이터를 1차원으로 만들어 주는 함수

a.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [65]:
a = np.arange(1,28).reshape(3,3,3)
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [76]:
#flatten = ravel과 같은 함수입니다. 


np.ravel(a)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [75]:
a = np.arange(1,28).reshape(27)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

# 랜덤값 생성.

In [79]:
#0에서 1사이의 값을 랜덤하게 생성
#균등분포랜덤



np.random.rand(5,5)

array([[0.22278452, 0.69349622, 0.37387292, 0.41966812, 0.22962369],
       [0.92138156, 0.51090442, 0.33170663, 0.5319882 , 0.05479123],
       [0.27027541, 0.14183009, 0.17825605, 0.97969326, 0.2225819 ],
       [0.95492779, 0.54468123, 0.85800403, 0.28605845, 0.56416334],
       [0.97392411, 0.85991896, 0.3903774 , 0.53388342, 0.18029495]])

In [80]:
#텐서플로우에서 사용
#정규분포랜덤
#중간 값이 0이고 편차가 1

np.random.randn(5,5)

array([[ 0.27335118,  0.23841213, -0.15754317, -1.06886392,  1.54617311],
       [ 0.11276002, -0.3196385 , -1.16612828,  2.26833531, -0.6766447 ],
       [ 0.34741704,  1.27268881,  1.19014438,  0.51274308, -0.95380612],
       [ 1.16696091, -2.87246021,  0.43293741,  0.30636426, -0.88802191],
       [-2.27909349, -1.57617077, -1.02666702,  1.57321624,  1.86978551]])

In [86]:
#정수 랜덤값

np.random.randint(0,10,size = (100,))

array([0, 0, 7, 0, 9, 7, 1, 7, 5, 6, 2, 7, 1, 3, 4, 3, 1, 6, 4, 8, 6, 0,
       9, 2, 4, 2, 6, 3, 8, 6, 4, 4, 8, 7, 1, 8, 0, 1, 5, 2, 0, 5, 2, 4,
       6, 4, 4, 6, 5, 0, 0, 1, 6, 0, 1, 0, 3, 2, 0, 5, 2, 0, 5, 9, 0, 3,
       9, 8, 5, 1, 1, 6, 8, 8, 4, 8, 6, 5, 3, 5, 4, 1, 8, 9, 0, 6, 0, 4,
       6, 8, 7, 9, 4, 4, 5, 9, 0, 9, 7, 2])

In [108]:
#랜덤 선택 #로또 번호 찍기// 중복제거가 필요하다. 


np.random.choice([100,200,300,400,500,600],size = (2,))

array([500, 100])

In [116]:
#로또번호를 생성해내는 코드를 작성

a = np.arange(1,46)

for i in range(10):
    print(np.random.choice(a,size =(6, ),replace =False))

[20 23 44 28 31 24]
[16 20 41 19  6 17]
[13 12  9 17 20 34]
[41 36  6 10 43 38]
[24 25 33  9 40  4]
[27 11 41 29 39  4]
[22 40 45 25 36 23]
[44 40 20 18 16 36]
[42 32 18 35 30 10]
[ 6 20 39 15 16  8]


# 인덱싱과 슬라이싱

In [126]:
#indexing
x = np.arange(0,160,10)
print(x)
x[3]

[  0  10  20  30  40  50  60  70  80  90 100 110 120 130 140 150]


30

In [123]:
#slicing
#끝값은 제외가 된다. 

x[2:6]





array([20, 30, 40, 50])

In [124]:
x[0:16:2]

array([  0,  20,  40,  60,  80, 100, 120, 140])

In [125]:
#맨 뒤에 값.

x[-1]

150

# 2차원 배열에서의 슬라이싱

In [129]:
x = np.arange(25).reshape(5,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [131]:
#2차원 indexing
#파이썬
x[2][2]

12

In [133]:
#넘파이
x[2,2]

12

In [136]:
x[4,4] = 99999
x

array([[    0,     1,     2,     3,     4],
       [    5,     6,     7,     8,     9],
       [   10,    11,    12,    13, 99999],
       [   15,    16,    17,    18,    19],
       [   20,    21,    22,    23, 99999]])

In [137]:
#2차원 슬라이싱

x[0,0:5]

array([0, 1, 2, 3, 4])

In [138]:
x[1,0:5]

array([5, 6, 7, 8, 9])

In [145]:
x[4,:-2]

array([20, 21, 22])

In [146]:
x = np.arange(36).reshape(6,6)
x

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [166]:
#빨강
# 행 전체에서 2번째 열에 있는거 전부다..
x[0:,2]

array([ 2,  8, 14, 20, 26, 32])

In [152]:
#주황
#0번째 행에서 2부터 5까지
x[0,2:5]

array([2, 3, 4])

In [172]:
#파랑
#4번째행부터 마지막 행까지 중에서 4부터 마지막까지 .
x[4:,4:]


array([[28, 29],
       [34, 35]])

In [168]:
#초록
#2부터 6행중에 2스텝을 밟아라. 
#그중에서 선택된 곳은 0부터 6까지 2칸씩 선택해라. 

x[2:6:2, 0:6:2]

array([[12, 14, 16],
       [24, 26, 28]])