In [2]:
import numpy as np

In [4]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
a/2

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [10]:
a//2

array([[0, 0, 1],
       [1, 2, 2],
       [3, 3, 4]], dtype=int32)

In [12]:
a/0

C:\Users\qlswl\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Users\qlswl\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[nan, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [14]:
a = np.arange(9).reshape(3,3)
np.mean(a)   #평균값.

4.0

In [15]:
np.max(a) #최대값.

8

In [17]:
np.min(a) #최소값

0

In [18]:
np.sum(a)

36

In [20]:
np.cumsum(a) #1차원으로 바꾼후 하나씩 계속 더해가라. 

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36], dtype=int32)

In [21]:
#조건 인덱싱

a[a>3]

array([4, 5, 6, 7, 8])

In [22]:
a[(a>3)&(a<7)]

array([4, 5, 6])

In [26]:
np.savetxt('a.csv',a,delimiter= ',')  #a 값 저장하기


In [45]:
y = np.loadtxt('a.csv',delimiter= ',', dtype='float32')
y

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]], dtype=float32)

In [35]:
a = np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [37]:
a.shape

(3, 3)

In [46]:
a = np.expand_dims(a, axis = -1)

In [47]:
a.shape

(3, 3, 1)

In [51]:
a = np.expand_dims(a, axis = 1)

In [50]:
a.shape

(1, 1, 3, 3, 1)

In [41]:
b = a[np.newaxis,...]#차원 추가
b.shape

(1, 3, 3)

In [43]:
b = a[np.newaxis,...,np.newaxis]#양옆으로 차원추가
b.shape

(1, 3, 3, 1)

In [44]:
#1인 축을 제거해준다. 

b = b.squeeze()
b.shape

(3, 3)